name: goreleaser

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.5
      - name: Build
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --skip=announce,publish --config .goreleaser/darwin.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jqless-darwin
          path: dist/jqless*

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.5
      - name: Install cross-compiler libraries
        run: sudo apt-get install -y gcc-aarch64-linux-gnu
      - name: Build
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --skip=announce,publish --config .goreleaser/linux.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jqless-linux
          path: dist/jqless*

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.5
      - name: Build
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --skip=announce,publish --config .goreleaser/windows.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jqless-windows
          path: dist/jqless*

  release:
    needs: [build-darwin, build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.5
      - name: Make directory
        run: |
          mkdir -p ./jqless-build/darwin
          mkdir -p ./jqless-build/linux
          mkdir -p ./jqless-build/windows
      - name: Download darwin binaries
        uses: actions/download-artifact@v4
        with:
          name: jqless-darwin
          path: ./jqless-build/darwin
      - name: Download linux binaries
        uses: actions/download-artifact@v4
        with:
          name: jqless-linux
          path: ./jqless-build/linux
      - name: Download windows binaries
        uses: actions/download-artifact@v4
        with:
          name: jqless-windows
          path: ./jqless-build/windows
      - name: Merge checksum files
        run: |
          cd ./jqless-build
          cat ./darwin/jqless*checksums.txt >> checksums.txt
          cat ./linux/jqless*checksums.txt >> checksums.txt
          cat ./windows/jqless*checksums.txt >> checksums.txt
          rm ./darwin/jqless*checksums.txt
          rm ./linux/jqless*checksums.txt
          rm ./windows/jqless*checksums.txt
      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --config .goreleaser/release.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      - name: Upload checksum
        uses: actions/upload-artifact@v4
        with:
          name: release-checksums
          path: jqless-build/checksums.txt

  push:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: samsullivan/homebrew-samsullivan
          ref: 'main'
          token:  ${{ secrets.RELEASE_GITHUB_TOKEN }}
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot (jqless)"
          git config user.email "<>"
      - name: Download release checksums
        uses: actions/download-artifact@v4
        with:
          name: release-checksums
          path: ./checksums.txt
      - name: Make changes to jqless homebrew file
        run: |
          cp jqless.rb.template jqless.rb
          echo ${{ github.event.release.tag_name }} | sed 's/v//' |\
            xargs -I{} sed -i -e 's/%VERSION%/{}/g' jqless.rb
          grep Darwin_all checksums.txt | awk '{print $1}' |\
            xargs -I{} sed -i -e 's/%DARWIN_SHA%/{}/g' jqless.rb
          grep Linux_arm checksums.txt | awk '{print $1}' |\
            xargs -I{} sed -i -e 's/%LINUX_ARM_SHA%/{}/g' jqless.rb
          grep Linux_x86_64 checksums.txt | awk '{print $1}' |\
            xargs -I{} sed -i -e 's/%LINUX_INTEL_SHA%/{}/g' jqless.rb
          rm checksums.txt
          git add jqless.rb
          git commit -m ""
      - run: git push origin main