name: goreleaser

on: [pull_request]

permissions:
  contents: write

jobs:
  build-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.5
      - name: Build
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --skip=announce,publish,validate --config .goreleaser/darwin.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: jqless-darwin
          path: dist/jqless*

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.5
      - name: Install cross-compiler libraries
        run: sudo apt-get install -y gcc-aarch64-linux-gnu
      - name: Build
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --skip=announce,publish,validate --config .goreleaser/linux.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: jqless-linux
          path: dist/jqless*

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.5
      - name: Build
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --skip=announce,publish,validate --config .goreleaser/windows.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: jqless-windows
          path: dist/jqless*

  release:
    needs: [build-darwin, build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.5
      - name: Make directory
        run: |
          mkdir -p ./jqless-build/darwin
          mkdir -p ./jqless-build/linux
          mkdir -p ./jqless-build/windows
      - name: Download darwin binaries
        uses: actions/download-artifact@v4
        with:
          name: jqless-darwin
          path: ./jqless-build/darwin
      - name: Download linux binaries
        uses: actions/download-artifact@v4
        with:
          name: jqless-linux
          path: ./jqless-build/linux
      - name: Download windows binaries
        uses: actions/download-artifact@v4
        with:
          name: jqless-windows
          path: ./jqless-build/windows
      - name: Merge checksum file
        run: |
          cd ./jqless-build
          cat ./darwin/jqless*checksums.txt >> checksums.txt
          cat ./linux/jqless*checksums.txt >> checksums.txt
          cat ./windows/jqless*checksums.txt >> checksums.txt
          rm ./darwin/jqless*checksums.txt
          rm ./linux/jqless*checksums.txt
          rm ./windows/jqless*checksums.txt